name: github workflows with actions

on:
  push:

jobs:
  test-actions:
    name: test-actions
    runs-on: ubuntu-latest
    steps:
      - name: list files
        run: ls
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: list files after action
        run: ls
      - name: hello-world-action
        id: hello-world-action
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: "Kartik"
      - name: Print time of output
        run: echo "'greeting time:' ${{ steps.hello-world-action.outputs.time }} "
      - name: docker-action
        uses: docker://hello-world:latest




        
          
